#!/usr/bin/env bash
# A bash script that prints "Best School" and "Hi" on the 9th position

i=1

while [ $i -le 10 ]
do
    if [ $i -eq 9 ]
    then
        echo "Hi"
    else
        echo "Best School"
    fi

    (( i++ ))
done

