#!/usr/bin/env bash
# A Bash script that loops from 1 to 10 and displays different messages for specific iterations.

for i in {1..10}
do
    if [ $i -eq 4 ]
    then
        echo "Bad luck"
    elif [ $i -eq 8 ]
    then
        echo "Good luck"
    else
        echo "Best School"
    fi
done

