#!/usr/bin/env bash
#A shell script that prints superstitious numbers at iterations

i=1

while [ $i -le 20 ]
do
    case $i in
        4)
            echo "4 and then bad luck from China"
            ;;
        9)
            echo "9 and then bad luck from Japan"
            ;;
        17)
            echo "17 and then bad luck from Italy"
            ;;
        *)
            echo $i
            ;;
    esac

    (( i++ ))
done

