#!/usr/bin/env bash
# script that print th hours and minutes of a clock
hour=0

while [ $hour -le 12 ]
do
    minute=1

    while [ $minute -le 59 ]
    do
        printf "%02d:%02d\n" $hour $minute

        (( minute++ ))
    done

    (( hour++ ))
done

