#!/usr/bin/env bash
#a shekk script that prints the name of the files in the present working directory.

for file in *
do
    if [ -f "$file" ] && [[ "$file" != .* ]] && [[ "$file" == *-* ]]
    then
        basename=${file#*-}
        echo "$basename"
    fi
done

